### ISSUE TITLE
Add option to update goiplookup

### ISSUE THREAD

**Issue by crakerjac** [axllent/goiplookup#2]
There is already an option to update the GeoLite2 database.  Can there be an option to update goiplookup as well?  Then I can set up a cron job to ensure that both GeoLite2 and goiplookup are up to date.

**Comment by axllent** [comment]
I'm actually working on that option/functionality already, so yes :-)

**Comment by axllent** [comment]
I've just released 0.0.3 which includes a `self-update` option

**Comment by axllent** [comment]
Sorry, there is a bug in the path detection in 0.0.3, fix in progress but may take a day or so.

**Comment by axllent** [comment]
Fixed in 0.0.4
