### ISSUE TITLE
Show subnet details

### ISSUE THREAD

**Issue by Programie** [axllent/goiplookup#3]
The legacy geoiplookup utility shows details about the subnet of the given IP address if `-i` has been passed. goiplookup on the other side uses the `-i` option to only show the ISO country code.

Example:

```
$ geoiplookup -i 8.8.8.8
GeoIP Country Edition: US, United States
  ipaddr: 8.8.8.8
  range_by_ip:  8.7.245.0 - 8.14.223.255
  network:      8.8.0.0 - 8.11.255.255 ::14
  ipnum: 134744072
  range_by_num: 134739200 - 135192575
  network num:  134742016 - 135004159 ::14
```

```
$ goiplookup -i 8.8.8.8
US
```

Getting the subnet of the specific IP address was a big benefit of the geoiplookup utility.

Would it be possible to implement the same functionality as previously known from the legacy utility?

**Comment by axllent** [comment]
I'd love to, but I don't think this is possible to be honest, as either the new mmdb country format (or possibly the geoip library I'm using) doesn't appear to provide any of that information: https://github.com/oschwald/geoip2-golang/blob/347ca45869a87337a71b11efe9b3043bc10df97f/reader.go#L136

If you're able to confirm that the new country mmdb format provides this data, then that would be a great help!

**Comment by Programie** [comment]
Weird, the subnet information are included in the CSV version of the GeoLite2 Country DB. So I guess there is nothing you can do from your side in implementing that feature.
