### ISSUE TITLE
Public maxmind DB url decomissioned

### ISSUE THREAD

**Issue by MarkGardiner** [axllent/goiplookup#5]
It seems for [legal reasons](https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/), the default `dbUpdateURL` used by the `./goiplookup db-update` command is no longer available.

It is easy enough to fix this by updating the `goiplookup.go:25`, `dbUpdateURL` value to be:
`dbUpdateURL = "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=<SIGN_UP_FOR_API_KEY_AND_ADD_HERE>&suffix=tar.gz"`
and running `make` (after substituting in your API key of course).

**Comment by axllent** [comment]
Thanks for the report and info Mark, I wasn't aware they had implemented this "feature". 

Hmm, I'm not sure what the consequences would be (if any) to embed a key in the source code/binary, vs the hassles of exporting (env) a key on runtime, or having to create a config.

I think I'll probably go with an exported key at build time so the binaries run as-is, but not embedded in the source code. I'll get this sorted in the next couple of days.

**Comment by MarkGardiner** [comment]
Thanks! I meant the above as a quick-fix for anybody who saw the same problem - I didn't know if there already was a properties file or environmental variable where the value could be set more logically.

I think its reasonable to pass the api key as a parameter to db-update at runtime.

Thanks for the awesome tool!

**Comment by axllent** [comment]
I have just released a new version of goiplookup which provides the license key requirements needed for database updating. The binary releases contain a working key (ie: no changes required), however if you are building from source then you will need to provide your own. More details/instructions on https://github.com/axllent/goiplookup#database-updates

Thanks again for the heads-up Mark!
